[48..51..58] in Test_2.scala
foo cannot be called with false
